---
- name: Installing Apache
  gather_facts: true
  # vars_files:
  #   - "apache_default.yml"
  #   - "apache_RedHat.yml"
  hosts: all
  become: true
  tasks:
    - name: Install apache on Amazon Linux
      yum:
        name: httpd
        state: latest
        update_cache: yes
      when: ansible_os_family=='amazon-linus'
    - name: Install apache on Ubuntu
      apt:
        name: apache2
        state: latest
        update_cache: yes
      when: ansible_facts['distribution']=='Ubuntu'







