---
- name: Class example on prom installatiom with ansible
  gather_facts: true
  host: amazonservers
  become: true
  
  tasks:
    - name: create premetheus user
      user:
        name: prometheus 
        append: true
        shell: /usr/bin/nologin
        system: true
        create_home: false
    
    - name: create premetheus directory
      file: 
        path: "{{item}}"
        state: directory
        mode: 0755 #chmod
        owner: prometheus
        group: prometheus
      loop:
        - /etc/prometheus
        - /var/lib/prometheus



    - name: download premetheus
      get_url:
        url: https://github.com/prometheus/prometheus/releases/download/v2.22.0/prometheus-2.22.0.linux-amd64.tar.gz 
        dest: /temp/ 
        mode: 0755 #chmod
        owner: prometheus
        group: prometheus

    - name: uncrchive premetheus and download - untar
      unarchive: 
        src: prometheus-2.22.0.linux-amd64.tar.gz #the file we are downloading
        dest: /temp/
        remote_src: yes
    
    - name: Step 5- Copy prometheus and promtool binary 
      copy: 
        src: "{{ item }}"
        dest: /usr/local/bin/
        owner: prometheus
        group: prometheus
        remote_src: yes
      loop: #  for every item in the loop, copy all item to dest and give the prop
        - /temp/prometheus-2.22.0.linux-amd64/premetheus
        - /temp/prometheus-2.22.0.linux-amd64/promtool

        


